models/Source.php
<?php

namespace app\models;

use yii\base\Model;
use Yii;

/**
 * Class Source
 * @package app\models
 *
 * @property string $filename
 */
class Source extends Model {

    /**
     * Holds datasources directory path
     */
    const PATH_SOURCES = '@runtime/sources/';

    /**
     * Holds file file nam
     * @var string
     */
    public $filename = '';

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['filename'], 'string'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'filename' => 'File name',
        ];
    }

    /**
     * Get list of sources
     *
     * @param boolean $useCache
     * @return array
     */
    public static function findAll($useCache = true)
    {
        static $sources = array();
        if(sizeof($sources) == 0 || !$useCache) {
            $dirPath = Yii::getAlias(static::PATH_SOURCES);
            $sources = [];
            if(file_exists($dirPath)) {
                $dh = opendir($dirPath);
                while ($file = readdir($dh)) {
                    if ($file == '.' || $file == '..') continue;
                    $info = pathinfo($file);
                    if ($info['extension'] != 'json') continue;
                    $sources[] = new Source(['filename' => $file]);
                }
                closedir($dh);
            }
        }
        return $sources;
    }

    /**
     * Uploads new data source
     *
     * @param array $fileData
     * @return Source
     */
    public static function uploadSource($fileData) {
        $dirPath = Yii::getAlias(static::PATH_SOURCES);
        if(!file_exists($dirPath)) mkdir($dirPath);

        $newDataSourceName = date('Y-m-d_His') . '.json';
        if(copy($fileData['tmp_name'], $dirPath . $newDataSourceName)) {
            return new Source(['filename' => $newDataSourceName]);
        }
        return null;
    }

    /**
     * Deletes existing data source
     *
     * @param string $fileName
     * @return boolean
     */
    public static function deleteSource($fileName) {
        $dirPath = Yii::getAlias(static::PATH_SOURCES);
        if(file_exists($dirPath . $fileName)) {
            unlink($dirPath . $fileName);
            return true;
        }
        return false;
    }

    /**
     * Checks existing data file
     *
     * @param string $fileName
     * @return boolean
     */
    public static function checkSource($fileName) {
        $dirPath = Yii::getAlias(static::PATH_SOURCES);
        return file_exists($dirPath . $fileName);
    }

    /**
     * Load existing data file
     *
     * @param string $fileName
     * @return boolean
     */
    public static function loadSource($fileName) {
        $dirPath = Yii::getAlias(static::PATH_SOURCES);
        if(!file_exists($dirPath . $fileName)) return [];

        $fileContents = file_get_contents($dirPath . $fileName);
        return (array)json_decode($fileContents);
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Source;
use app\widgets\Flashes;
use Yii;
use yii\base\Request;
use yii\web\Controller;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Shows presentation of data sources
     *
     * @return string
     */
    public function actionIndex()
    {
        /* @var \yii\web\Session $session */
        $session = Yii::$app->session;

        /* @var Request $request */
        $request = Yii::$app->request;


        /* @var Source $sources */
        $sources = Source::findAll();

        // Load saved configuration
        $sessData = $session->get('presentation', []);
        $firstSource = sizeof($sources) ? $sources[0]->filename : '';
        $selectedDataSource = !empty($sessData['data-source']) ? $sessData['data-source'] : $firstSource;
        $selectedViewType = isset($sessData['view-type']) ? $sessData['view-type'] : 0;

        // Get configuration selected by user
        $postDataSource = $request->post('data-source');
        if(!empty($postDataSource)) $selectedDataSource = $postDataSource;
        $postViewType = $request->post('view-type', -1);
        if($postViewType > -1) $selectedViewType = $postViewType;

        // Check configuration
        if(!Source::checkSource($selectedDataSource)) $selectedDataSource = $firstSource;
        if($selectedViewType < 0 || $selectedViewType > 2) $selectedViewType = 0;

        // Save configuration
        $sessData['data-source'] = $selectedDataSource;
        $sessData['view-type'] = $selectedViewType;
        $session->set('presentation', $sessData);

        return $this->render('index', [
            'selectedDataSource' => $selectedDataSource,
            'selectedViewType' => $selectedViewType,
            'sources' => $sources,
        ]);
    }
}

controllers/SourcesController.php
<?php

namespace app\controllers;

use app\models\Api;
use app\models\Client;
use app\models\Source;
use app\models\Venicle;
use app\widgets\Flashes;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;

class SourcesController extends Controller
{
    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Shows list of data sources
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Uploads new data source
     */
    public function actionUpload()
    {
        // Process data source upload
        $upload = isset($_POST['upload']);
        if($upload && isset($_FILES['new-data-source'])) {
            $fileData = $_FILES['new-data-source'];
            if($fileData['error']) {
                Flashes::setError('Data source upload error! Error code: ' . $fileData['error']);
            } else if(!file_exists($fileData['tmp_name'])) {
                Flashes::setError('Data source upload error! File does not exist!');
            } else {
                /** @var Source $result */
                $result = Source::uploadSource($fileData);
                if(!$result) {
                    Flashes::setError('Data source upload error!');
                } else {
                    Flashes::setSuccess('New data source saved as `' . $result->filename . '`.');
                }
            }
        }
        return $this->redirect(['index']);
    }

    /**
     * Deletes data source from list
     */
    public function actionDelete()
    {
        $file = Yii::$app->request->get('file', '');
        if($file) {
            $result = Source::deleteSource($file);
            if(!$result) {
                Flashes::setError('Data source deletion error!');
            } else {
                Flashes::setSuccess('Data source was successfully deleted! File: ' . $file);
            }
        }
        return $this->redirect(['index']);
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;

use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode(Yii::$app->name . ($this->title ? ': ' . $this->title : '')) ?></title>
    <?php $this->head() ?>
    <!-- ChartJS -->
    <script src="//www.chartjs.org/dist/2.7.0/Chart.bundle.js"></script>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar navbar-default navbar-fixed-top',
        ],
    ]);

    $menuItems = [
        ['label' => Yii::t('app', 'Data presentation'), 'url' => ['/site/index']],
        ['label' => Yii::t('app', 'Data sources'), 'url' => ['/sources/index']],
    ];

    echo Nav::widget([
        'options' => ['class' => 'nav navbar-nav'],
        'items'   => $menuItems,
    ]);

    NavBar::end();
    ?>

    <div class="container main">
        <section class="messages">
            <?php echo \app\widgets\Flashes::widget() ?>
        </section>

        <section class="content">
            <?= $content ?>
        </section>
    </div>
</div>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/site/_chart.php
<?php
$bgColors = array(
'rgba(255, 99, 132, 0.5)', // red
'rgba(255, 159, 64, 0.5)', // orange
'rgba(255, 205, 86, 0.5)', // yellow
'rgba(75, 192, 192, 0.5)', // green
'rgba(54, 162, 235, 0.5)', //blue
'rgba(153, 102, 255, 0.5)', // purple
'rgba(201, 203, 207, 0.5)', // grey
);
$borderColors = array(
'rgb(255, 99, 132)', // red
'rgb(255, 159, 64)', // orange
'rgb(255, 205, 86)', // yellow
'rgb(75, 192, 192)', // green
'rgb(54, 162, 235)', //blue
'rgb(153, 102, 255)', // purple
'rgb(201, 203, 207)', // grey
);
$dataSets = array();
$i = 0;
foreach((array)$rows as $rowIndex => $rowData) {
$dataSet = array();
$dataSet['label'] = $rowIndex;
$dataSet['backgroundColor'] = isset($bgColors[$i]) ? $bgColors[$i] : $bgColors[0];
$dataSet['borderColor'] = isset($borderColors[$i]) ? $borderColors[$i] : $borderColors[0];
$dataSet['borderWidth'] = 1;
$dataSet['data'] = $rowData;
$dataSets[] = (object)$dataSet;
$i++;
}
?>
<canvas id="canvas"></canvas>
<script>
    'use strict';
    <?php if($lines) {
    foreach ($dataSets as $datasetIndex => $dataSet) $dataSets[$datasetIndex]->fill = false;
    ?>
    window.onload = function() {
        var ctx = document.getElementById("canvas").getContext("2d");
        window.myBar = new Chart(ctx, {
            type: 'line',
            data: {
                labels: <?= json_encode($columns) ?>,
                datasets: <?= json_encode($dataSets) ?>
            },
            options: {
                responsive: true,
                legend: {
                    position: 'top',
                },
                title: {
                    display: true,
                    text: ''
                }
            }
        });

    };
    <?php } else { ?>
    window.onload = function() {
        var ctx = document.getElementById("canvas").getContext("2d");
        window.myBar = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: <?= json_encode($columns) ?>,
                datasets: <?= json_encode($dataSets) ?>
            },
            options: {
                responsive: true,
                title:{
                    display:true,
                    text:''
                },
                tooltips: {
                    mode: 'index',
                    intersect: false,
                },
                hover: {
                    mode: 'nearest',
                    intersect: true
                },
                scales: {
                    xAxes: [{
                        display: true,
                        scaleLabel: {
                            display: true,
                            labelString: 'Month'
                        }
                    }],
                    yAxes: [{
                        display: true,
                        scaleLabel: {
                            display: true,
                            labelString: 'Value'
                        }
                    }]
                }
            }
        });

    };
    <?php } ?>
</script>

views/site/_table.php
<div class="table-responsive">
    <table class="table table-bordered table-striped">
        <thead>
        <tr>
            <?php foreach($columns as $columnIndex => $columnName) { ?>
                <th><?= $columnName ?></th>
            <?php } ?>
        </tr>
        </thead>
        <tbody>
        <?php foreach((array)$rows as $rowIndex => $rowData) { ?>
            <tr>
                <?php foreach($columns as $columnIndex => $columnName) { ?>
                    <td><?= isset($rowData[$columnIndex]) ? $rowData[$columnIndex] : 0 ?></td>
                <?php } ?>
            </tr>
        <?php } ?>
        </tbody>
    </table>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="error-page">
    <h2 class="headline text-yellow"><?php echo property_exists($exception, 'statusCode') ? $exception->statusCode : '&nbsp;' ?></h2>

    <div class="error-content">
        <h3><i class="fa fa-warning text-yellow"></i> Oops! <?php echo $message ?></h3>
    </div>

</div>

views/site/index.php
<?php

use app\models\Source;

/* @var yii\base\View $this */
/* @var string $selectedDataSource */
/* @var integer $selectedViewType */
/* @var Source[] $sources*/

$viewTypes = array(
    0 => 'Table',
    1 => 'Lines',
    2 => 'Bars',
);

// Load JSON data
$columns = $rows = null;
if(!empty($selectedDataSource)) {
    $data = Source::loadSource($selectedDataSource);
    $columns = $data['Columns'] ?: null;
    $rows = $data['Rows'] ?: null;
}
?>
<div class="row">
    <!-- Configuration block START -->
    <div class="col-sm-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Configuration</h3>
            </div>
            <div class="panel-body">
                <form action="?" method="post">
                    <input type="hidden" name="_csrf" value="<?=Yii::$app->request->getCsrfToken()?>" />

                    <div class="form-group">
                        <label for="data-source">Data source:</label>
                        <select class="form-control" id="data-source" name="data-source">
                            <?php foreach ($sources as $source) { ?>
                                <option<?= $selectedDataSource == $source->filename ? ' selected="selected"' : '' ?>><?= $source->filename ?></option>
                            <?php } ?>
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="view-type">View type:</label>
                        <select class="form-control" id="view-type" name="view-type">
                            <?php foreach ($viewTypes as $viewIdx => $viewType) { ?>
                                <option value="<?= $viewIdx ?>"<?= $selectedViewType == $viewIdx ? ' selected="selected"' : '' ?>><?= $viewType ?></option>
                            <?php } ?>
                        </select>
                    </div>

                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Refresh&nbsp;&raquo;</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- Configuration block END -->
    <!-- Presentation block START -->
    <div class="col-sm-9">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">Presentation</h3>
            </div>
            <div class="panel-body">
                <?php if(is_null($rows)) { ?>
                    No data loaded.
                <?php } else { ?>
                    <?php if($selectedViewType == 0) { // Table view
                        echo $this->render('_table', [
                            'columns' => $columns,
                            'rows' => $rows,
                        ]);
                    } else if($selectedViewType == 1) { // Lines
                        echo $this->render('_chart', [
                            'columns' => $columns,
                            'rows' => $rows,
                            'lines' => true,
                        ]);
                    } else { // Bars
                        echo $this->render('_chart', [
                            'columns' => $columns,
                            'rows' => $rows,
                            'lines' => false,
                        ]);
                    }
                    ?>
                <?php } ?>
            </div>
        </div>
    </div>
    <!-- Presentation block END -->
</div>

views/sources/index.php
<?php

use app\models\Source;
use yii\helpers\Url;

?>

<div class="row">
    <!-- Data source upload form START -->
    <div class="col-sm-6">
        <div class="well">
            <form enctype="multipart/form-data" method="post" action="<?= Url::to(['sources/upload']) ?>">
                <input type="hidden" name="_csrf" value="<?=Yii::$app->request->getCsrfToken()?>" />
                <div class="form-group">
                    <label for="new-data-source">Upload new data source</label>
                    <input type="file" name="new-data-source" class="form-control-file" id="new-data-source">
                </div>
                <div class="form-group">
                    <button type="submit" name="upload" class="btn btn-primary">Upload&nbsp;&raquo;</button>
                </div>
            </form>
        </div>
    </div>
    <!-- Data source upload form END -->
    <!-- Data source list START -->
    <div class="col-sm-6">
        <ul class="list-group">
            <?php foreach (Source::findAll() as $fileModel) { ?>
            <li class="list-group-item"><?= $fileModel->filename ?>
                <div class="pull-right"><a href="<?= Url::to(['sources/delete', 'file' => $fileModel->filename]) ?>" onclick="return confirm('Are You sure?')" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-remove-sign"></i></a></div>
            </li>
        <?php } ?>
        </ul>
    </div>
    <!-- Data source list END -->
</div>